export enum ListOperationType {
    CREATE_LIST = 'CREATE_LIST',
    ADD_ITEM = 'ADD_ITEM',
    INDENT_ITEM = 'INDENT_ITEM',
    OUTDENT_ITEM = 'OUTDENT_ITEM',
    TOGGLE_LIST_TYPE = 'TOGGLE_LIST_TYPE',
    DEACTIVATE_LIST_MODE = 'DEACTIVATE_LIST_MODE',
    REMOVE_LIST = 'REMOVE_LIST'
}