export enum TableOperationType {
  CREATE_TABLE = 'CREATE_TABLE',
  DELETE_TABLE = 'DELETE_TABLE',
  INSERT_ROW = 'INSERT_ROW',
  DELETE_ROW = 'DELETE_ROW',
  INSERT_COLUMN = 'INSERT_COLUMN',
  DELETE_COLUMN = 'DELETE_COLUMN',
  EDIT_CELL = 'EDIT_CELL',
}
